[system]
compatible=suderra-os-x86_64
bootloader=grub
grubenv=/boot/EFI/BOOT/grubenv
bundle-formats=verity
statusfile=/data/rauc/status.ini

[keyring]
path=/etc/rauc/keyring.pem

[slot.rootfs.0]
device=/dev/disk/by-partlabel/rootfs-a
type=raw
bootname=A

[slot.rootfs-verity.0]
device=/dev/disk/by-partlabel/rootfs-a-verity
type=raw
parent=rootfs.0

[slot.rootfs.1]
device=/dev/disk/by-partlabel/rootfs-b
type=raw
bootname=B

[slot.rootfs-verity.1]
device=/dev/disk/by-partlabel/rootfs-b-verity
type=raw
parent=rootfs.1
